---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: keycloak
  name: keycloak-http
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 8443
      name: http
      protocol: TCP
      targetPort: 8443
  selector:
    app: keycloak
  sessionAffinity: None
  type: ClusterIP
