---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  labels:
    app: keycloak
  name: keycloak-ingress
  namespace: {{ .Values.namespace }}
spec:
  defaultBackend:
    service:
      name: keycloak-http
      port:
        number: 8443
  rules:
    - host: keycloak.{{ .Values.hostname }}
      http:
        paths:
          - backend:
              service:
                name: keycloak-http
                port:
                  number: 8443
            path: /
            pathType: ImplementationSpecific
